CREATE TABLE AGENDA
(
	ID int NOT NULL primary key auto_increment,
	NOME VARCHAR(255) NOT NULL,
	STATUS CHAR(1) NOT NULL
);

CREATE TABLE AGENDAMENTO
(
	ID int not null primary key auto_increment,
	ID_AGENDA int not null,
	TITULO VARCHAR(255) not null,
	DATA_HORA_INICIO DATETIME NOT NULL,
	DATA_HORA_FIM DATETIME NOT NULL,
	STATUS VARCHAR(20),
	CONSTRAINT FK_AGENDA FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID)
);